{"name": "test_token_de_autenticação_válido", "status": "broken", "statusDetails": {"message": "pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"Que eu tenho um usuário criado\". Line 4 in scenario \"Token de autenticação válido\" in the feature \"/Users/bi003709/Documents/Projeto-desafio/features/api_auth.feature\"", "trace": "E   pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"Que eu tenho um usuário criado\". Line 4 in scenario \"Token de autenticação válido\" in the feature \"/Users/bi003709/Documents/Projeto-desafio/features/api_auth.feature\"\nAll traceback entries are hidden. Pass `--full-trace` to see hidden and internal frames."}, "description": "/Users/bi003709/Documents/Projeto-desafio/features/api_auth.feature: Token de autenticação válido", "start": 1746735836837, "stop": 1746735836838, "uuid": "da31b708-6d97-4c12-9f8e-524e5cd20282", "historyId": "f05f4481a28eee2a850e9e92171e978a", "testCaseId": "f05f4481a28eee2a850e9e92171e978a", "fullName": "tests.api.test_auth#test_token_de_autenticação_válido", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "rec-a-011826"}, {"name": "thread", "value": "10666-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_auth"}]}